### ISSUE TITLE
Code Review of Hashtables

### ISSUE THREAD

**Issue by SWHarrison** [galkochris/CS-1.2-Intro-Data-Structures#1]
- All tests pass, nice job!
- Fantastic comments explaining each block of code!
- Run time analysis of keys, values and items should be O(n). Since you are looping through each bucket that has on average L items, then b * L is n. Another way to think of it is that you are getting each value in the entire hash table once, or n items.
- I recommend going back and expanding on your runtime analysis of get, set, contains and delete to explain the best case scenario, and be more explicit about the average and worst case scenarios.

**Comment by galkochris** [comment]
Thank you! updated the information to reflect proper avg., best and worst case for the final 4, with a little more explanation. Also fixed the time complexity of the first three, to reflect the proper time complexity of 0(n).
